name: Update README Image

on:
  schedule:
    - cron: '0 11 * * 1'
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Random Image in README
        run: |
          # Daftar tautan gambar RAW yang akan diacak
          IMAGES=(
            "https://raw.githubusercontent.com/TaufiqStark/TaufiqStark/main/img/yuki-souo_cute-peace.png"
            "https://raw.githubusercontent.com/TaufiqStark/TaufiqStark/main/img/yuki-souo_cute-pose.png"
            "https://raw.githubusercontent.com/TaufiqStark/TaufiqStark/main/img/yuki-souo_pleading-face.png"
            "https://raw.githubusercontent.com/TaufiqStark/TaufiqStark/main/img/yuki-souo_sharp_devil-face.png"
            "https://raw.githubusercontent.com/TaufiqStark/TaufiqStark/main/img/yuki-souo_side-eye.png"
          )

          # Pilih tautan gambar secara acak dari daftar di atas
          RANDOM_IMAGE=${IMAGES[RANDOM % ${#IMAGES[@]}]}

          # Cari baris yang berisi ID unik, lalu ganti tautan di tag <img> di dalam baris tersebut
          sed -i "/id=\"random-profile-image\"/ {
            s|src=\".*\"|src=\"${RANDOM_IMAGE}\"|
          }" README.md

          echo "Berhasil mengganti tautan gambar menjadi: ${RANDOM_IMAGE}"
          # echo "--- Isi README.md setelah perubahan ---"
          # cat README.md

      - name: Commit and Push Changes
        run: |
          if [[ -n $(git status --porcelain README.md) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "(readme): update random image"
            git push
            echo "Perubahan berhasil di-commit dan di-push."
          else
            echo "Tidak ada perubahan, tidak perlu di-commit."
          fi
